### ISSUE TITLE
List of available commands

### ISSUE THREAD

**Issue by mat-l** [coolchip/node-red-contrib-viera#1]
Thanks a lot for this Node-Red package. It works perfect for me.
Just one question: Is there a list of commands that are available?
Best
Matl

**Comment by coolchip** [comment]
Hello, thank you very much.

This node depends on viera.js. so you should be able to use every command, that viera.js supports:
https://github.com/samuelmatis/viera.js/blob/master/codes.txt

**Comment by coolchip** [comment]
Also added this to the README.md
