### ISSUE TITLE
What happens if TV is turned off?

### ISSUE THREAD

**Issue by joachimmarder** [coolchip/node-red-contrib-viera#2]
What is supposed to happen or to be returned for getVolume() if the TV is turned off?

**Comment by coolchip** [comment]
Unfortunatelly nothing. U are also not able to turn it on.

**Comment by JeroenVBH** [comment]
The TV will turn on by sending a digit number e.g. 1

**Comment by coolchip** [comment]
Really? Cool!
Seems that this is working only with some models.
