### ISSUE TITLE
Support for new PIN enabled Panasonic TVs

### ISSUE THREAD

**Issue by nodecentral** [coolchip/node-red-contrib-viera#4]

**Comment by coolchip** [comment]
Sorry, I've no idea how to do that.

**Comment by nodecentral** [comment]
Hi, more details related to the remote control PIN/encryption requirement is here - https://github.com/florianholzapfel/panasonic-viera

**Comment by coolchip** [comment]
Thank you very much for the link.
Somebody here who want's to implement this in js? ;-)
