### ISSUE TITLE
Read current input/source: AV, TV, HDMI1, HDMI2, HDMI3

### ISSUE THREAD

**Issue by circa1665** [coolchip/node-red-contrib-viera#5]
Currently the viera read node can get the volume and mute state - would be great if it could also read the current input, e.g AV, TV, HDMI1, HDMI2, HDMI3 etc.

**Comment by ChienTing** [comment]
Read power status
Just better

**Comment by coolchip** [comment]
I hope that the tip from ChienTing helped.

**Comment by JeroenVBH** [comment]
I have the same question. Please forgive me for being dumb here, but what does ChienTing mean with "Read power status"?
At the moment I made my code to ask for volume feedback. If it does get a reply, I know the TV is on. If it doesn't, it's off.
I'm also interested in the current input to sync my button feedback on a UI.

**Comment by coolchip** [comment]
Unfortunately I also don't know it.
